#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env.production}"
COMPOSE_FILE="${COMPOSE_FILE:-$ROOT_DIR/infra/docker/docker-compose.prod.images.yml}"
IMAGE_ENV_FILE="${IMAGE_ENV_FILE:-}"
IMAGE_TAR="${IMAGE_TAR:-}"
SKIP_PULL="${SKIP_PULL:-false}"
PRUNE_OLD_IMAGES="${PRUNE_OLD_IMAGES:-true}"
IMAGE_PRUNE_UNTIL="${IMAGE_PRUNE_UNTIL:-168h}"

usage() {
  cat <<'USAGE'
Usage: scripts/deploy-prod-images.sh [options]

Deploy production services using prebuilt images. This script is intended to run
on the server and does not build images.

Options:
  --image-env FILE   Source image variables generated by build-prod-images.sh --save.
  --load FILE        docker load the image tar before restarting services.
  --skip-pull        Do not pull images from registry. Use with --load or local images.

Environment:
  API_IMAGE, ADMIN_WEB_IMAGE and IMAGE_TAG can be set in .env.production or --image-env.
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --image-env)
      IMAGE_ENV_FILE="${2:?missing image env file}"
      shift 2
      ;;
    --load)
      IMAGE_TAR="${2:?missing image tar file}"
      SKIP_PULL=true
      shift 2
      ;;
    --skip-pull)
      SKIP_PULL=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

cd "$ROOT_DIR"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required on the server" >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose plugin is required on the server" >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo ".env.production is missing. Create it from .env.production.example first." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
if [ -n "$IMAGE_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$IMAGE_ENV_FILE"
fi
set +a

required_vars=(
  POSTGRES_PASSWORD
  SECRET_KEY
  CORS_ORIGINS
  NEXT_PUBLIC_API_BASE_URL
)

for name in "${required_vars[@]}"; do
  if [ -z "${!name:-}" ]; then
    echo "$name is required in .env.production" >&2
    exit 1
  fi
done

if [ -n "$IMAGE_TAR" ]; then
  echo "Loading images from $IMAGE_TAR"
  docker load -i "$IMAGE_TAR"
  rm -f "$IMAGE_TAR"
fi
if [ -n "$IMAGE_ENV_FILE" ]; then
  rm -f "$IMAGE_ENV_FILE"
fi

# Deployment uploads can be resumed in chunks. Remove stale chunks after the
# new image is available; database and application volumes are not touched.
if [ -d "$ROOT_DIR/upload-slices" ]; then
  find "$ROOT_DIR/upload-slices" -type f -mmin +180 -delete
fi

echo "Using images:"
echo "  API_IMAGE=${API_IMAGE:-fin-hub-api:${IMAGE_TAG:-latest}}"
echo "  ADMIN_WEB_IMAGE=${ADMIN_WEB_IMAGE:-fin-hub-admin-web:${IMAGE_TAG:-latest}}"

if [ "$SKIP_PULL" != "true" ]; then
  echo "Pulling service images..."
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" pull
fi

echo "Starting production services with prebuilt images..."
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d

if [ "$PRUNE_OLD_IMAGES" = "true" ]; then
  echo "Removing unused Docker images older than $IMAGE_PRUNE_UNTIL..."
  docker image prune -af --filter "until=$IMAGE_PRUNE_UNTIL"
fi

echo "Service status:"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps

echo "Running smoke checks..."
if [ -x "$ROOT_DIR/scripts/smoke-prod.sh" ]; then
  "$ROOT_DIR/scripts/smoke-prod.sh" "${SMOKE_BASE_URL:-http://127.0.0.1}"
else
  curl -sf "${SMOKE_BASE_URL:-http://127.0.0.1}/api/health" >/dev/null
  echo "✅ API health passed"
fi
